### ISSUE TITLE
Website is returning 500 Internal Server Error

### ISSUE THREAD

**Issue by trivikr** [mcollina/nodejs-download-stats#12]
Website: https://nodedownloads.nodeland.dev/

<details>
<summary>Screenshot</summary>

<img width="1004" alt="Screenshot 2024-02-21 at 6 55 42 PM" src="https://github.com/mcollina/nodejs-download-stats/assets/16024985/1b2d55e3-1b73-4468-ac02-28d9ac3ca63a">

</details>

**Comment by mcollina** [comment]
Fixed
