### ISSUE TITLE
Skip the stats for the latest month as they're incomplete

### ISSUE THREAD

**Issue by trivikr** [mcollina/nodejs-download-stats#7]
### Is your feature request related to a problem? Please describe.

The download stats for the latest month are incomplete, so they're shown in the graph as less than previous month.

<details>
<summary>Example screenshot from Nov 21st</summary>

<img width="612" alt="Screenshot 2023-11-21 at 5 27 27 PM" src="https://github.com/mcollina/nodejs-download-stats/assets/16024985/a1b484aa-828d-4201-a524-019b5852724e">

</details>

In the above screenshot, the numbers for Nov'23 are 2/3rd of that for Oct'23 not because of Node.js was downloaded less times, but because November isn't finished yet. This can give wrong idea to the viewer that Node.js downloads have reduced in the current month.

### Describe the solution you'd like

Skip the stats for the latest month as they're incomplete

### Describe alternatives you've considered

Provide an option to the user to include/exclude of ongoing month.

**Comment by mcollina** [comment]
This would be amazing to do. Would you like to send a PR?

**Comment by trivikr** [comment]
> Would you like to send a PR?

Will do.
