### ISSUE TITLE
Skip showing incomplete downloads for the first month

### ISSUE THREAD

**Issue by trivikr** [mcollina/nodejs-download-stats#9]
### Is your request related to a problem? Please describe.

The downloads for the first month are incomplete, so it appears like there's a huge jump in the downloads in the second month

<details>
<summary>Screenshot</summary>

<img width="610" alt="Screenshot 2023-11-23 at 7 49 43 AM" src="https://github.com/mcollina/nodejs-download-stats/assets/16024985/dfcb89ab-9b51-4fd6-85eb-e19b70d807b9">

</details>

Note that downloads for 2021-03 is are low. That's because in [access logs summaries](https://storage.googleapis.com/access-logs-summaries-nodejs/), only three days of data is available for `2021-03` and the number is incomplete.

### Describe the solution you'd like
If data is not available for all days of the month in the first month, skip showing it.

### Describe alternatives you've considered
N/A

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue?
